"use client";
import { SitePageHeader } from "../SitePageHeader";
import { useEffect, useRef, useState } from "react";
import { useWorkspace } from "../../lib/builder/use-workspace";
import { themeAppearance } from "../../lib/builder/appearance";
import { useAuth } from "./AuthProvider";
import { AuthIcon } from "./AuthIcon";
import { SlideLink } from "../SlideLink";
import { avatars, ProfileAvatar } from "./ProfileAvatar";
import { api, clearCsrf } from "../../lib/api/client";
import type { AvatarStyle } from "../../lib/auth/model";
const sections = [{ id: "profile", label: "Profil" }, { id: "notifications", label: "Bildirimler" }, { id: "security", label: "Güvenlik" }, { id: "connected", label: "Bağlı Hesaplar" }, { id: "sessions", label: "Oturumlar" }, { id: "delete", label: "Hesabı Sil" }] as const;
type Section = typeof sections[number]["id"];
export function AccountPage() {
  const auth = useAuth(); const { workspace } = useWorkspace(); const appearance = themeAppearance(workspace.applied);
  const [avatar, setAvatar] = useState<AvatarStyle>("initials");
  const [active, setActive] = useState<Section>("profile"); const [name, setName] = useState(""); const [confirmation, setConfirmation] = useState("");
  const [deleting, setDeleting] = useState(false); const dialog = useRef<HTMLDialogElement>(null); const deletion = useRef<HTMLElement>(null);
  useEffect(() => { setName(auth.session?.profile.name ?? ""); setAvatar(auth.session?.profile.avatar ?? "initials"); }, [auth.session?.profile.name, auth.session?.profile.avatar, auth.session?.profile.id]);
  useEffect(() => { if (deleting && !dialog.current?.open) dialog.current?.showModal(); else if (!deleting && dialog.current?.open) dialog.current.close(); }, [deleting]);
  useEffect(() => { if (!auth.session) setDeleting(false); }, [auth.session]);
  useEffect(() => { setActive("profile"); setConfirmation(""); }, [auth.session?.profile.id]);
  const [sessions, setSessions] = useState<{ id: string; current: boolean; deviceLabel: string; lastSeenAt: string; expiresAt: string }[]>([]);
  const [connections, setConnections] = useState<{ provider: string; connectedAt: string }[]>([]);
  const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [newPassword,setNewPassword]=useState(""),[repeatPassword,setRepeatPassword]=useState(""),[newEmail,setNewEmail]=useState("");
  const profile = auth.session?.profile;
  useEffect(() => {
    setSessions([]); setConnections([]); setPassword(""); setError("");
    if(!profile?.verified) return;
    const abort = new AbortController();
    const load = active === "sessions" ? api<{ items: typeof sessions }>("/me/sessions", { signal: abort.signal }).then(data => setSessions(data.items)) : active === "connected" ? api<{ items: typeof connections }>("/me/connections", { signal: abort.signal }).then(data => setConnections(data.items)) : Promise.resolve();
    void load.catch(error => { if(!abort.signal.aborted) setError(error instanceof Error ? error.message : "Yüklenemedi."); });
    return () => abort.abort();
  }, [profile?.id, profile?.verified, active]);
  async function run(work: () => Promise<void>) { if(busy) return; setBusy(true); setError(""); try { await work(); } catch(error) { setError(error instanceof Error ? error.message : "İşlem tamamlanamadı."); } finally { setBusy(false); } }

  return <main className={`${appearance.className} account-page`} style={appearance.style}>
    <SitePageHeader theme={workspace.applied} />
    <div className="account-layout"><div className="account-heading"><p className="eyebrow">KENDİ ALANIN</p><h1>Hesap</h1><p>Profilin, tercihlerin ve oturumun bir arada.</p></div>
      {!auth.ready ? <p role="status">Oturum yükleniyor…</p> : !profile ? <section className="account-empty"><AuthIcon kind="user" /><h2>Hesabına giriş yap.</h2><p>Kitaplığını ve kişisel ayarlarını burada yönetebilirsin.</p><button className="auth-primary" onClick={() => auth.openAuth()}>Giriş yap</button></section> : !profile.verified ? <section className="account-empty"><h2>E-posta adresini doğrula</h2><p>Kitaplığın ve hesap ayarların doğrulamadan sonra açılır.</p><button className="auth-primary" onClick={()=>auth.openAuth("verify")}>Doğrulama bağlantısı gönder</button></section> : <div className="account-columns">
        <nav className="account-sidebar" aria-label="Hesap bölümleri">{sections.filter(section => profile.role !== "owner" || section.id !== "delete").map(section => <button type="button" key={section.id} aria-current={active === section.id ? "page" : undefined} onClick={() => { setActive(section.id); if (section.id === "delete") deletion.current?.scrollIntoView({ behavior: document.documentElement.dataset.motion === "off" ? "auto" : "smooth", block: "center" }); }}>{section.label}</button>)}</nav>
        <div className="account-content"><p className="account-demo-note">Hesap ve kişisel veriler sunucuda tutulur.</p>
          <section aria-label={sections.find(s => s.id === active)?.label} className="account-section">
            {active === "profile" && <><h2>Profil</h2><p>Sana nasıl hitap edelim?</p><form onSubmit={e => { e.preventDefault(); void run(async () => { if (await auth.updateProfile({ name, avatar })) auth.notify("Profil güncellendi"); }); }}><fieldset className="avatar-picker"><legend>Profil avatarın</legend><div className="avatar-preview"><ProfileAvatar name={name || profile.name} avatar={avatar} /><span>Seni kitaplığında ve hesap menüsünde temsil eder.</span></div><div className="avatar-options">{avatars.map(option => <label key={option.id} title={option.label}><input type="radio" name="avatar" value={option.id} checked={avatar === option.id} onChange={() => setAvatar(option.id)} aria-label={option.label} /><ProfileAvatar name={name || profile.name} avatar={option.id} /></label>)}</div></fieldset><label className="auth-field">Adın<input autoComplete="name" maxLength={80} value={name} onChange={e => setName(e.target.value)} /></label><label className="auth-field">E-posta<input type="email" value={profile.email} readOnly /><span className="auth-field-hint">E-posta değişikliği kimliğini yeniden doğrulamanı gerektirir.</span></label><button className="auth-primary" type="submit" disabled={!name.trim() || (name.trim() === profile.name && avatar === (profile.avatar ?? "initials"))}>Değişiklikleri kaydet</button></form>{!profile.verified && <div className="account-inline"><span>E-posta doğrulama önizlemesi tamamlanmadı.</span><button type="button" onClick={() => auth.openAuth("verify")}>Doğrulamayı incele</button></div>}</>}
            {active === "notifications" && <><h2>Yayın bildirimleri</h2><p>Yazın yayına alındığında e-posta ile haber verelim.</p><label className="account-notification-toggle"><span><strong>Yayınlandığında e-posta al</strong><small>Bu tercih tüm yazıların için geçerlidir.</small></span><input type="checkbox" role="switch" checked={profile.publicationEmail ?? true} disabled={busy} onChange={e => { const enabled = e.target.checked; void run(async () => { if (await auth.updateProfile({ publicationEmail: enabled })) auth.notify(enabled ? "Yayın bildirimleri açıldı" : "Yayın bildirimleri kapatıldı"); }); }} /></label><p className="auth-field-hint">Bu tercih bütün yazıların için geçerlidir.</p></>}
            {active === "security" && <><h2>Güvenlik</h2><p>Hassas işlemler için kimliğini yeniden doğrula. Doğrulama beş dakika geçerlidir.</p><form onSubmit={e => { e.preventDefault(); void run(async () => { await api("/auth/reauthenticate", { method: "POST", body: { password } }); clearCsrf(); setPassword(""); auth.notify("Kimlik doğrulandı"); }); }}><label className="auth-field">Güncel şifren<input type="password" autoComplete="current-password" maxLength={128} value={password} disabled={busy} onChange={e => setPassword(e.target.value)} /></label><button className="auth-primary" disabled={busy || !password}>Kimliğimi doğrula</button></form>{profile.role!=="owner" && <button type="button" className="account-outline" disabled={busy} onClick={()=>void run(async()=>{const data=await api<{authorizationUrl:string}>("/auth/google/start",{method:"POST",body:{purpose:"reauth",returnTo:"/hesap"}});window.location.assign(data.authorizationUrl);})}>Google ile kimliğimi doğrula</button>}
<form onSubmit={event=>{event.preventDefault();void run(async()=>{await api("/me/password",{method:"PUT",body:{password:newPassword,passwordConfirmation:repeatPassword}});setNewPassword("");setRepeatPassword("");clearCsrf();await auth.refresh();auth.notify("Şifre güncellendi. Tekrar giriş yap.");});}}><label className="auth-field">Yeni şifre<input type="password" autoComplete="new-password" minLength={12} maxLength={128} value={newPassword} onChange={event=>setNewPassword(event.target.value)}/></label><label className="auth-field">Yeni şifre tekrarı<input type="password" autoComplete="new-password" minLength={12} maxLength={128} value={repeatPassword} onChange={event=>setRepeatPassword(event.target.value)}/></label><button className="auth-primary" disabled={busy||newPassword.length<12||newPassword!==repeatPassword}>Şifreyi değiştir</button></form>
<form onSubmit={event=>{event.preventDefault();void run(async()=>{await api("/me/email-change",{method:"POST",body:{email:newEmail}});setNewEmail("");auth.notify("Yeni adresine doğrulama bağlantısı gönderilecek.");});}}><label className="auth-field">Yeni e-posta<input type="email" autoComplete="email" maxLength={254} value={newEmail} onChange={event=>setNewEmail(event.target.value)} required/></label><button className="auth-primary" disabled={busy||!newEmail}>E-posta değişikliği iste</button></form>
<SlideLink className="account-outline" href="/sifremi-unuttum">Şifremi unuttum ↗</SlideLink><div className="account-inline"><span>E-posta</span><span>{profile.verified ? "Doğrulandı" : "Doğrulama bekleniyor"}</span></div></>}
            {active === "connected" && <><h2>Bağlı Hesaplar</h2>{profile.role === "owner" ? <p>Studio hesabı Google ile giriş kullanmaz.</p> : <><p>Bağlantı işlemleri için önce Güvenlik bölümünde kimliğini yeniden doğrula.</p><div className="account-inline"><span>Google <small>{connections.some(c => c.provider === "google") ? "Bağlı" : "Bağlı değil"}</small></span><button type="button" disabled={busy} onClick={() => void run(async () => { if(connections.some(c => c.provider === "google")) { await api("/me/connections/google", { method: "DELETE" }); setConnections([]); auth.notify("Bağlantı kaldırıldı"); } else { const data = await api<{ authorizationUrl: string }>("/me/connections/google/start", { method: "POST", body: { returnTo: "/hesap" } }); window.location.assign(data.authorizationUrl); } })}>{connections.some(c => c.provider === "google") ? "Bağlantıyı kaldır" : "Google hesabını bağla"}</button></div></>}</>}
            {active === "sessions" && <><h2>Oturumlar</h2><p>Aynı tarayıcıdaki bütün site sekmeleri ortak bir oturum kullanır.</p>{sessions.map(item => <div className="account-session" key={item.id}><strong>{item.deviceLabel} <span>{item.current ? "Geçerli oturum" : "Diğer oturum"}</span></strong><p>Son kullanım: {new Date(item.lastSeenAt).toLocaleString("tr-TR")}</p><p>Bitiş: {new Date(item.expiresAt).toLocaleString("tr-TR")}</p><button className="account-outline" type="button" disabled={busy} onClick={() => void run(async () => { await api(`/me/sessions/${item.id}`, { method: "DELETE" }); if(item.current) { clearCsrf(); await auth.refresh(); } else setSessions(list => list.filter(s => s.id !== item.id)); })}>Oturumu kapat</button></div>)}<button className="account-outline" type="button" disabled={busy} onClick={() => void run(async () => { await api("/me/sessions/revoke-others", { method: "POST" }); setSessions(list => list.filter(s => s.current)); auth.notify("Diğer oturumlar kapatıldı"); })}>Diğer oturumları kapat</button><p className="auth-field-hint">Toplu kapatma için önce Güvenlik bölümünde kimliğini yeniden doğrula.</p></>}
            {active === "delete" && <><h2>Hesabı Sil</h2><p>Aşağıdaki alandan hesabını kaldırabilirsin.</p></>}
          </section>
          {(error || auth.error) && <p role="alert" className="auth-field-error">{error || auth.error}</p>}
          {profile.role !== "owner" && <section className="account-delete" ref={deletion}><h2>Hesabı sil</h2><p>Profilin, kitaplığın ve kişisel notların kalıcı olarak kaldırılır.</p><button className="account-danger" type="button" onClick={() => { setConfirmation(""); setDeleting(true); }}>Hesabı sil</button></section>}
        </div>
      </div>}
    </div>
    <dialog ref={dialog} className={`${appearance.className} account-confirm`} style={appearance.style} aria-labelledby="delete-account-title" onCancel={() => setDeleting(false)} onClose={() => setDeleting(false)}><h2 id="delete-account-title">Hesabını silmek istiyor musun?</h2><p>Bu hesaba ait kitaplık, koleksiyonlar ve notlar kaldırılır. Önce Güvenlik bölümünde kimliğini yeniden doğrula; ardından e-posta adresini yaz.</p><label className="auth-field">E-posta adresin<input autoComplete="off" value={confirmation} onChange={e => setConfirmation(e.target.value)} /></label><div><button type="button" className="account-outline" autoFocus onClick={() => setDeleting(false)}>Vazgeç</button><button type="button" className="account-danger" disabled={!profile || confirmation.trim().toLowerCase() !== profile.email} onClick={() => void run(async () => { if (await auth.deleteAccount()) setDeleting(false); })}>Hesabı sil</button></div>{(error || auth.error) && <p role="alert" className="auth-field-error">{error || auth.error}</p>}</dialog>
  </main>;
}
