"use client";
import {useState,useEffect} from "react";
import {api} from "../../lib/api/client";
import {CoverPicker} from "./CoverPicker";
import { MediaUpload } from "./MediaUpload";
import { usePublicData } from "../api/PublicDataProvider";
import { PublicationSchedule } from "./PublicationSchedule";
import { articleCategories, articleDate } from "../../lib/articles/metadata";
import { topics, type Article } from "../../lib/content";
export function TextField({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean }) {
  return <label className="studio-field"><span>{label}</span>{multiline ? <textarea rows={5} value={value} onChange={(e) => onChange(e.target.value)} /> : <input value={value} onChange={(e) => onChange(e.target.value)} />}</label>;
}
export const articleFields = [["title", "Başlık"], ["excerpt", "Özet / abstract"], ["body", "Metin ve paragraflar"], ["figure", "Görsel"], ["cover", "Kapak"], ["seo", "Arama motorları"], ["code", "Kod örneği"], ["table", "Tablo"], ["meta", "Yazı bilgileri"], ["publication", "Yayın planı"], ["layout", "Sayfa düzeni"]] as const;
export function ArticleProperties({ article, field, onChange, allowSlugEdit = false, onSchedule, onCancelSchedule, scheduleDisabled = false }: { onSchedule?: () => void; onCancelSchedule?: () => void; scheduleDisabled?: boolean; allowSlugEdit?: boolean; article: Article; field: string; onChange: (a: Article) => void }) {
  const apiMode=!!usePublicData();
  const [categoryNames,setCategoryNames]=useState<string[]>(apiMode ? [...articleCategories(article)] : [...topics.slice(1)]);
  useEffect(()=>{if(!apiMode)return;let current=true;void api<{items:{name:string}[]}>("/studio/categories").then(data=>{if(current)setCategoryNames([...new Set([...data.items.map(c=>c.name),...articleCategories(article)])]);}).catch(()=>{});return()=>{current=false;};},[apiMode,article.serverId]);
  const ids=()=>article.paragraphIds ?? article.paragraphs.map((_,i)=>article.serverRecord?.document.blocks.filter(b=>b.type==="paragraph")[i]?.id ?? crypto.randomUUID());
  const update = (change: Partial<Article>) => onChange({ ...article, ...change });
  const presentation = article.presentation ?? { width: "comfortable", heading: "left", showMeta: true };
  if(field==="cover")return <CoverPicker type="article" id={article.serverId} version={article.serverVersion} privateContent={article.visibility==="private"} value={article.cover ?? article.serverRecord?.cover ?? {mode:"auto",assetId:null}} onChange={cover=>update({cover})}/>;
  if(field==="seo"){const seo=article.seo ?? article.serverRecord?.seo ?? {title:null,description:null,indexable:true};return <><TextField label="Arama motoru başlığı · boşsa yazı başlığı" value={seo.title ?? ""} onChange={title=>update({seo:{...seo,title:title||null}})}/><TextField label="Arama motoru açıklaması · boşsa özet" multiline value={seo.description ?? ""} onChange={description=>update({seo:{...seo,description:description||null}})}/><label className="document-checkbox"><input type="checkbox" checked={seo.indexable} onChange={e=>update({seo:{...seo,indexable:e.target.checked}})}/>Arama motorlarında yer alabilir</label><p className="property-note">Özel, taslak ve planlanmış yazılar bu seçimden bağımsız olarak indekslenmez.</p></>;}
  if (field === "publication") return <PublicationSchedule article={article} onChange={onChange} onSchedule={onSchedule} onCancel={onCancelSchedule} disabled={scheduleDisabled} />;
  if (field === "title") return <TextField label="Yazı başlığı" value={article.title} onChange={(title) => update({ title })} />;
  if (field === "excerpt") return <TextField label="Özet / abstract" value={article.excerpt} multiline onChange={(excerpt) => update({ excerpt })} />;
  if (field === "meta") return <>{apiMode && <label className="document-checkbox"><input type="checkbox" checked={article.visibility==="private"} onChange={event=>update({visibility:event.target.checked?"private":"public",status:"draft",scheduledAt:undefined})} />Özel yazı · yalnızca ben görebilirim</label>}<TextField label="Üst başlık" value={article.eyebrow} onChange={(eyebrow) => update({ eyebrow })} /><fieldset className="studio-category-options"><legend>Kategoriler</legend>{categoryNames.map((topic) => { const selected = articleCategories(article); return <label key={topic}><input type="checkbox" checked={selected.includes(topic)} disabled={selected.length === 1 && selected.includes(topic)} onChange={(e) => { const categories = e.target.checked ? [...selected, topic] : selected.filter((c) => c !== topic); update({ categories, category: categories[0] }); }} /><span>{topic}</span></label>; })}</fieldset><label className="studio-field"><span>Yazı tarihi</span><input type="date" required value={articleDate(article)} onChange={(e) => update({ publishedAt: e.target.value })} /></label><p className="property-note">Yazılar en yeni tarihten başlayarak sıralanır. Serideki bölüm sırası değişmez.</p><label className="studio-field"><span>Okuma süresi (dakika)</span><input type="number" readOnly={apiMode} min={1} max={240} value={article.minutes} onChange={(e) => update({ minutes: Number(e.target.value) })} /></label>{apiMode && <p className="property-note">Okuma süresi yazının metninden otomatik hesaplanır.</p>}<>{(allowSlugEdit || apiMode) && <TextField label="Kalıcı bağlantı adı" value={article.slug} onChange={(slug) => update({ slug })} />}<p className="property-note">Kalıcı bağlantı: /yazilar/{article.slug}</p></></>;
  if (field === "layout") return <><label className="studio-field"><span>İçerik genişliği</span><select value={presentation.width} onChange={(e) => update({ presentation: { ...presentation, width: e.target.value as "comfortable" | "wide" } })}><option value="comfortable">Rahat okuma</option><option value="wide">Geniş içerik</option></select></label><label className="studio-field"><span>Başlık hizası</span><select value={presentation.heading} onChange={(e) => update({ presentation: { ...presentation, heading: e.target.value as "left" | "center" } })}><option value="left">Sola hizalı</option><option value="center">Ortalanmış</option></select></label><label className="document-checkbox"><input type="checkbox" checked={presentation.showMeta} onChange={(e) => update({ presentation: { ...presentation, showMeta: e.target.checked } })} />Kategoriler, tarih ve okuma süresini göster</label></>;
  if (field === "figure") return <>{apiMode && <MediaUpload onUpload={src=>update({figure:{src,alt:article.figure?.alt ?? "",caption:article.figure?.caption ?? "",width:1200,height:800}})} />}{article.figure ? <><TextField label="Görsel adresi" value={article.figure.src} onChange={(src) => update({ figure: { ...article.figure!, src } })} /><TextField label="Alternatif metin" value={article.figure.alt} onChange={(alt) => update({ figure: { ...article.figure!, alt } })} /><TextField label="Görsel açıklaması" value={article.figure.caption} onChange={(caption) => update({ figure: { ...article.figure!, caption } })} /><button className="studio-remove" onClick={() => update({ figure: undefined })}>Görseli kaldır</button></> : !apiMode && <button className="studio-secondary" onClick={() => update({ figure: { src: "/assets/thinking-loop.svg", alt: "", caption: "", width: 1200, height: 600 } })}>Görsel ekle</button>}<p className="property-note">Yüklediğin görsel yalnızca bu yazının erişim kurallarına göre sunulur.</p></>;
  if (field === "code") return <><TextField label="Kod örneği" multiline value={article.code ?? ""} onChange={(code) => update({ code: code || undefined })} /><p className="property-note">Boş bırakılırsa kod bölümü görünmez.</p></>;
  if (field === "table") return article.table ? <><TextField label="Tablo açıklaması" value={article.table.caption} onChange={(caption) => update({ table: { ...article.table!, caption } })} />{article.table.columns.map((column, i) => <TextField key={i} label={`Sütun ${i + 1}`} value={column} onChange={(v) => update({ table: { ...article.table!, columns: article.table!.columns.map((c, j) => j === i ? v : c) } })} />)}{article.table.rows.map((row, r) => <fieldset className="document-table-row" key={r}><legend>Satır {r + 1}</legend>{row.map((cell, c) => <TextField key={c} label={article.table!.columns[c] || `Sütun ${c + 1}`} value={cell} onChange={(v) => update({ table: { ...article.table!, rows: article.table!.rows.map((item, i) => i === r ? item.map((old, j) => j === c ? v : old) : item) } })} />)}<button onClick={() => update({ table: { ...article.table!, rows: article.table!.rows.filter((_, i) => i !== r) } })}>Satırı kaldır</button></fieldset>)}<button className="studio-secondary" onClick={() => update({ table: { ...article.table!, rows: [...article.table!.rows, article.table!.columns.map(() => "")] } })}>Satır ekle</button><button className="studio-secondary" disabled={article.table.columns.length >= 20} onClick={() => update({ table: { ...article.table!, columns: [...article.table!.columns, "Yeni sütun"], rows: article.table!.rows.map((r) => [...r, ""]) } })}>Sütun ekle</button><button className="studio-remove" onClick={() => update({ table: undefined })}>Tabloyu kaldır</button></> : <button className="studio-secondary" onClick={() => update({ table: { caption: "", columns: ["Başlık", "Açıklama"], rows: [["", ""]] } })}>Tablo ekle</button>;
  const selectedIndex = field.startsWith("paragraph-") ? Number(field.slice(10)) : null;
  return <>{article.paragraphs.map((paragraph, index) => (selectedIndex === null || index === selectedIndex) && <div key={index} className="document-paragraph"><TextField label={`Paragraf ${index + 1}`} value={paragraph} multiline onChange={(value) => update({ paragraphs: article.paragraphs.map((p, i) => i === index ? value : p) })} /><div className="document-order">{([-1, 1] as const).map((direction) => <button key={direction} disabled={index + direction < 0 || index + direction >= article.paragraphs.length} aria-label={`Paragraf ${index + 1} ${direction === -1 ? "yukarı" : "aşağı"}`} onClick={() => { const paragraphs = [...article.paragraphs]; [paragraphs[index], paragraphs[index + direction]] = [paragraphs[index + direction], paragraphs[index]]; const paragraphIds=[...ids()];[paragraphIds[index],paragraphIds[index+direction]]=[paragraphIds[index+direction],paragraphIds[index]];update({ paragraphs,paragraphIds }); }}>{direction === -1 ? "↑" : "↓"}</button>)}<button disabled={article.paragraphs.length === 1} onClick={() => update({ paragraphs: article.paragraphs.filter((_, i) => i !== index),paragraphIds:ids().filter((_,i)=>i!==index) })}>Paragrafı kaldır</button></div></div>)}<button className="studio-secondary" onClick={() => update({ paragraphs: [...article.paragraphs, "Yeni paragraf."],paragraphIds:[...ids(),crypto.randomUUID()] })}>Paragraf ekle</button></>;
}
