"use client";
import { PublicationSchedule } from "./PublicationSchedule";
import { articleCategories, articleDate } from "../../lib/articles/metadata";
import { type Article } from "../../lib/content";
import { ArticleCategoryField } from "./ArticleCategoryField";
import { ImageUpload } from "./ImageUpload";
import { CoverField } from "./CoverSearch";
export function TextField({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean }) {
  return <label className="studio-field"><span>{label}</span>{multiline ? <textarea rows={5} value={value} onChange={(e) => onChange(e.target.value)} /> : <input value={value} onChange={(e) => onChange(e.target.value)} />}</label>;
}
export const articleFields = [["title", "Başlık"], ["excerpt", "Özet / abstract"], ["cover", "Kapak görseli"], ["body", "Metin ve paragraflar"], ["figure", "Görsel"], ["code", "Kod örneği"], ["table", "Tablo"], ["meta", "Yazı bilgileri"], ["publication", "Yayın planı"], ["layout", "Sayfa düzeni"]] as const;
export function ArticleProperties({ article, field, onChange, allowSlugEdit = false, onSchedule, onCancelSchedule, scheduleDisabled = false }: { onSchedule?: () => void; onCancelSchedule?: () => void; scheduleDisabled?: boolean; allowSlugEdit?: boolean; article: Article; field: string; onChange: (a: Article) => void }) {
  const update = (change: Partial<Article>) => onChange({ ...article, ...change });
  const presentation = article.presentation ?? { width: "comfortable", heading: "left", showMeta: true };
  if (field === "publication") return <><label className="document-checkbox"><input type="checkbox" checked={article.visibility === "private"} onChange={(e) => update({ visibility: e.target.checked ? "private" : "public" })} />Özel yazı · yalnız sen görebilirsin</label><p className="property-note">Özel yazı yayımlanamaz ve planlanamaz; ziyaretçi listelerinde, aramada, site haritasında ve bağlantısında görünmez. Kamuya açmak için işareti kaldırıp kaydet, sonra yayımla.</p>{article.visibility !== "private" && <PublicationSchedule article={article} onChange={onChange} onSchedule={onSchedule} onCancel={onCancelSchedule} disabled={scheduleDisabled} />}</>;
  if (field === "title") return <TextField label="Yazı başlığı" value={article.title} onChange={(title) => update({ title })} />;
  if (field === "cover") return <CoverField cover={article.coverUrl} resource={article.id && article.version !== undefined ? { type: "article", id: article.id, version: article.version } : null} privateContent={article.visibility === "private"} suggestedQuery={article.title} previewAlt="Yazı kapağı önizlemesi" onChange={(coverUrl) => update({ coverUrl })} />;
  if (field === "excerpt") return <TextField label="Özet / abstract" value={article.excerpt} multiline onChange={(excerpt) => update({ excerpt })} />;
  if (field === "meta") return <><TextField label="Üst başlık" value={article.eyebrow} onChange={(eyebrow) => update({ eyebrow })} /><ArticleCategoryField article={article} onChange={update} /><label className="studio-field"><span>Yazı tarihi</span><input type="date" required value={articleDate(article)} onChange={(e) => update({ publishedAt: e.target.value })} /></label><p className="property-note">Yazılar en yeni tarihten başlayarak sıralanır. Serideki bölüm sırası değişmez.</p><label className="studio-field"><span>Okuma süresi (dakika)</span><input type="number" min={1} max={240} value={article.minutes} onChange={(e) => update({ minutes: Number(e.target.value) })} /></label><>{allowSlugEdit && <TextField label="Kalıcı bağlantı adı" value={article.slug} onChange={(slug) => update({ slug })} />}<p className="property-note">Kalıcı bağlantı: /yazilar/{article.slug}</p></></>;
  if (field === "layout") return <><label className="studio-field"><span>İçerik genişliği</span><select value={presentation.width} onChange={(e) => update({ presentation: { ...presentation, width: e.target.value as "comfortable" | "wide" } })}><option value="comfortable">Rahat okuma</option><option value="wide">Geniş içerik</option></select></label><label className="studio-field"><span>Başlık hizası</span><select value={presentation.heading} onChange={(e) => update({ presentation: { ...presentation, heading: e.target.value as "left" | "center" } })}><option value="left">Sola hizalı</option><option value="center">Ortalanmış</option></select></label><label className="document-checkbox"><input type="checkbox" checked={presentation.showMeta} onChange={(e) => update({ presentation: { ...presentation, showMeta: e.target.checked } })} />Kategoriler, tarih ve okuma süresini göster</label></>;
  if (field === "figure") return <>{article.figure ? <><TextField label="Görsel adresi" value={article.figure.src} onChange={(src) => update({ figure: { ...article.figure!, src } })} /><TextField label="Alternatif metin" value={article.figure.alt} onChange={(alt) => update({ figure: { ...article.figure!, alt } })} /><TextField label="Görsel açıklaması" value={article.figure.caption} onChange={(caption) => update({ figure: { ...article.figure!, caption } })} /><ImageUpload label="Görseli değiştir" onUploaded={(src) => update({ figure: { ...article.figure!, src } })} /><button className="studio-remove" onClick={() => update({ figure: undefined })}>Görseli kaldır</button></> : <ImageUpload label="Görsel yükle" onUploaded={(src) => update({ figure: { src, alt: "", caption: "", width: 1200, height: 675 } })} />}<p className="property-note">JPEG veya PNG yükle (en fazla 10 MiB). Sunucu görseli yeniden kodlar ve konum gibi gizli bilgileri siler. Site içi /assets/ yolları da kullanılabilir.</p></>;
  if (field === "code") return <><TextField label="Kod örneği" multiline value={article.code ?? ""} onChange={(code) => update({ code: code || undefined })} /><p className="property-note">Boş bırakılırsa kod bölümü görünmez.</p></>;
  if (field === "table") return article.table ? <><TextField label="Tablo açıklaması" value={article.table.caption} onChange={(caption) => update({ table: { ...article.table!, caption } })} />{article.table.columns.map((column, i) => <TextField key={i} label={`Sütun ${i + 1}`} value={column} onChange={(v) => update({ table: { ...article.table!, columns: article.table!.columns.map((c, j) => j === i ? v : c) } })} />)}{article.table.rows.map((row, r) => <fieldset className="document-table-row" key={r}><legend>Satır {r + 1}</legend>{row.map((cell, c) => <TextField key={c} label={article.table!.columns[c] || `Sütun ${c + 1}`} value={cell} onChange={(v) => update({ table: { ...article.table!, rows: article.table!.rows.map((item, i) => i === r ? item.map((old, j) => j === c ? v : old) : item) } })} />)}<button onClick={() => update({ table: { ...article.table!, rows: article.table!.rows.filter((_, i) => i !== r) } })}>Satırı kaldır</button></fieldset>)}<button className="studio-secondary" onClick={() => update({ table: { ...article.table!, rows: [...article.table!.rows, article.table!.columns.map(() => "")] } })}>Satır ekle</button><button className="studio-secondary" disabled={article.table.columns.length >= 20} onClick={() => update({ table: { ...article.table!, columns: [...article.table!.columns, "Yeni sütun"], rows: article.table!.rows.map((r) => [...r, ""]) } })}>Sütun ekle</button><button className="studio-remove" onClick={() => update({ table: undefined })}>Tabloyu kaldır</button></> : <button className="studio-secondary" onClick={() => update({ table: { caption: "", columns: ["Başlık", "Açıklama"], rows: [["", ""]] } })}>Tablo ekle</button>;
  const selectedIndex = field.startsWith("paragraph-") ? Number(field.slice(10)) : null;
  return <>{article.paragraphs.map((paragraph, index) => (selectedIndex === null || index === selectedIndex) && <div key={index} className="document-paragraph"><TextField label={`Paragraf ${index + 1}`} value={paragraph} multiline onChange={(value) => update({ paragraphs: article.paragraphs.map((p, i) => i === index ? value : p) })} /><div className="document-order">{([-1, 1] as const).map((direction) => <button key={direction} disabled={index + direction < 0 || index + direction >= article.paragraphs.length} aria-label={`Paragraf ${index + 1} ${direction === -1 ? "yukarı" : "aşağı"}`} onClick={() => { const paragraphs = [...article.paragraphs]; [paragraphs[index], paragraphs[index + direction]] = [paragraphs[index + direction], paragraphs[index]]; update({ paragraphs }); }}>{direction === -1 ? "↑" : "↓"}</button>)}<button disabled={article.paragraphs.length === 1} onClick={() => update({ paragraphs: article.paragraphs.filter((_, i) => i !== index) })}>Paragrafı kaldır</button></div></div>)}<button className="studio-secondary" onClick={() => update({ paragraphs: [...article.paragraphs, "Yeni paragraf."] })}>Paragraf ekle</button></>;
}
