import { topics, type Topic } from "../../lib/content";
import type { PageBlock } from "../../lib/builder/model";

function Field({ label, value, onChange, multiline = false, maxLength = 160 }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; maxLength?: number }) {
  return <label className="studio-field"><span>{label}</span>{multiline ? <textarea value={value} maxLength={maxLength} rows={4} onChange={(event) => onChange(event.target.value)} /> : <input value={value} maxLength={maxLength} onChange={(event) => onChange(event.target.value)} />}</label>;
}
export function BlockProperties({ block, onChange, onManageSeries }: { block: PageBlock; onChange: (block: PageBlock) => void; onManageSeries?: () => void }) {
  switch (block.kind) {
    case "header": return <p className="property-note">Site adını genel ayarlardan değiştirebilirsin. Menü, sayfandaki yazı, proje ve hakkımda bloklarından oluşur.</p>;
    case "intro": return <><label className="studio-field"><span>Giriş kompozisyonu</span><select value={block.layout} onChange={(event) => onChange({ ...block, layout: event.target.value as Extract<PageBlock, { kind: "intro" }>["layout"] })}><option value="statement">Büyük başlık · açık defter</option><option value="centered">Ortalanmış · dergi kapağı</option><option value="split">İki sütun · manifesto</option></select></label><Field label="Üst başlık" value={block.eyebrow} maxLength={120} onChange={(eyebrow) => onChange({ ...block, eyebrow })} /><Field label="Başlık" value={block.title} onChange={(title) => onChange({ ...block, title })} /><Field label="Giriş metni" value={block.description} multiline maxLength={2000} onChange={(description) => onChange({ ...block, description })} /></>;
    case "scene": return <><p className="property-note">Bu sahnenin karakter görseli, halkası ve koreografisi bütün olarak korunur. Başlıkları ve açıklamanı değiştirebilirsin. Altına yazı akışı veya başka bölümler ekleyebilirsin.</p><Field label="Başlık" value={block.title} onChange={(title) => onChange({ ...block, title })} /><Field label="Vurgulu satır" value={block.emphasis} onChange={(emphasis) => onChange({ ...block, emphasis })} /><Field label="Giriş metni" value={block.description} multiline maxLength={2000} onChange={(description) => onChange({ ...block, description })} /></>;
    case "articles": return <><Field label="Bölüm başlığı" value={block.title} onChange={(title) => onChange({ ...block, title })} /><label className="studio-field"><span>İçerik kaynağı / kategori</span><select value={block.category} onChange={(event) => onChange({ ...block, category: event.target.value as Topic })}>{topics.map((topic) => <option key={topic}>{topic}</option>)}</select></label><label className="studio-field"><span>Görünüm</span><select value={block.display} onChange={(event) => onChange({ ...block, display: event.target.value as "rows" | "cards" })}><option value="rows">Editoryal satırlar</option><option value="cards">Kartlar</option></select></label><label className="studio-field"><span>İçerik yükleme</span><select value={block.loading} onChange={(event) => onChange({ ...block, loading: event.target.value as "all" | "progressive" })}><option value="progressive">Kaydırdıkça yükle</option><option value="all">Hepsini göster</option></select></label><p className="property-note">Ortak yazı koleksiyonunu gösterir. Tema değişse de yazılar ve bağlantıları aynı kalır.</p></>;
    case "series": return <><Field label="Bölüm başlığı" value={block.title} onChange={(title) => onChange({ ...block, title })} /><label className="studio-field"><span>Seri görünümü</span><select value={block.display} onChange={(event) => onChange({ ...block, display: event.target.value as "cards" | "list" })}><option value="cards">Yolculuk kartları</option><option value="list">Sıralı liste</option></select></label><p className="property-note">Ziyaretçiye açık serileri gösterir. Bölümleri ve sıralamayı Seriler alanından yönetebilirsin.</p>{onManageSeries && <button className="studio-secondary" onClick={onManageSeries}>Seri içeriklerini düzenle →</button>}</>;
    case "quote": return <><label className="studio-field"><span>Alıntı sunumu</span><select value={block.display} onChange={(event) => onChange({ ...block, display: event.target.value as Extract<PageBlock, { kind: "quote" }>["display"] })}><option value="band">Tam genişlikte bant</option><option value="card">Çerçeveli düşünce kartı</option></select></label><Field label="Alıntı / düşünce" value={block.text} multiline maxLength={2000} onChange={(text) => onChange({ ...block, text })} /><Field label="Kaynak / imza" value={block.attribution} maxLength={120} onChange={(attribution) => onChange({ ...block, attribution })} /></>;
    case "about": return <><Field label="Bölüm başlığı" value={block.title} onChange={(title) => onChange({ ...block, title })} /><Field label="Tanışma metni" value={block.text} multiline maxLength={2000} onChange={(text) => onChange({ ...block, text })} /></>;
    case "projects": return <><Field label="Bölüm başlığı" value={block.title} onChange={(title) => onChange({ ...block, title })} /><p className="property-note">Projeler eklendiğinde bu bölümden gösterilecek. Şimdilik boş durumunu görebilirsin.</p></>;
    case "footer": return <Field label="İmza metni" value={block.text} onChange={(text) => onChange({ ...block, text })} />;
  }
}
