"use client";
import {useEffect,useRef,useState} from "react";
import {api} from "../../lib/api/client";
import type {ArticleRecord} from "../../lib/api/studio";
import {MediaUpload} from "./MediaUpload";
type Cover=ArticleRecord["cover"];
type Job={id:string;state:string;errorCode?:string;candidates:{assetId:string;thumbnailUrl:string;sourceUrl:string;photographer:string;licenseUrl:string}[]};
export function CoverPicker({value,onChange,type,id,version,privateContent=false}:{value:Cover;onChange:(cover:Cover)=>void;type:"article"|"series";id?:string;version?:number;privateContent?:boolean}) {
 const [query,setQuery]=useState(""),[job,setJob]=useState<Job|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");const generation=useRef(0);
 useEffect(()=>{generation.current++;setJob(null);setError("");return()=>{generation.current++;};},[id]);
 useEffect(()=>{if(!job || job.state!=="PENDING")return;const abort=new AbortController();let attempts=0;const timer=setInterval(()=>{if(++attempts>60){clearInterval(timer);setError("Kapak araması sürüyor. Daha sonra yeniden deneyebilirsin.");return;}void api<Job>(`/studio/cover-jobs/${job.id}`,{signal:abort.signal}).then(setJob).catch(e=>{if(!abort.signal.aborted){clearInterval(timer);setError(e.message);}});},2000);return()=>{clearInterval(timer);abort.abort();};},[job?.id,job?.state]);
 async function search(){if(!id || version===undefined || busy)return;const current=generation.current;setBusy(true);setError("");try{const result=await api<Job>("/studio/cover-jobs",{method:"POST",idempotencyKey:crypto.randomUUID(),body:{resourceType:type,resourceId:id,resourceVersion:version,query:query.trim()||null}});if(current===generation.current)setJob({...result,candidates:[]});}catch(e){if(current===generation.current)setError(e instanceof Error?e.message:"Kapak aranamadı.");}finally{if(current===generation.current)setBusy(false);}}
 return <><label className="studio-field"><span>Kapak</span><select value={value.mode} onChange={e=>{onChange({mode:e.target.value as Cover["mode"],assetId:null});setJob(null);}}><option value="auto">Otomatik kapak ara</option><option value="manual">Görsel yükle</option><option value="none">Kapak kullanma</option></select></label>{value.mode==="manual" && <MediaUpload onUpload={src=>onChange({mode:"manual",assetId:src.split("/").at(-1)!})}/>} {value.mode==="auto"&&<><label className="studio-field"><span>Arama konusu{privateContent?" · zorunlu":""}</span><input value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></label><p className="property-note">{id?privateContent?"Özel yazının başlığı sağlayıcıya gönderilmez. Arama konusunu sen belirle.":"Arama konusu boşsa kayıtlı başlık kullanılır.":"Kapak aramadan önce içeriği kaydet."} Arama için yapılandırılmış Pexels bağlantısı gerekir.</p><button type="button" className="studio-secondary" disabled={!id||busy||privateContent&&!query.trim()||job?.state==="PENDING"} onClick={()=>void search()}>Kapak ara</button></>}{job?.state==="PENDING"&&<p role="status">Kapaklar aranıyor…</p>}{job?.state==="FAILED"&&<p role="alert">Kapak araması tamamlanamadı. Yeniden deneyebilirsin.</p>}{job?.state==="READY"&&job.candidates.map(candidate=><div key={candidate.assetId}><button type="button" onClick={()=>{onChange({mode:"manual",assetId:candidate.assetId});setJob(null);}}><img src={candidate.thumbnailUrl} width={180} height={100} alt="Kapak adayı"/></button><small><a href={candidate.sourceUrl} rel="noopener noreferrer" target="_blank">{candidate.photographer} · Pexels</a></small></div>)}{value.assetId&&<><img src={`/api/v1/media/${value.assetId}`} width={240} alt="Seçili kapak"/><button className="studio-secondary" type="button" onClick={()=>onChange({mode:"none",assetId:null})}>Kapağı kaldır</button><p className="property-note">Seçimini uygulamak için içeriği kaydet.</p></>}{error&&<p className="property-note" role="alert">{error}</p>}</>;
}
