"use client";
import type { Article } from "../../lib/content";
import { insertChapterByCreation } from "../../lib/articles/metadata";
import { type BlogSeries } from "../../lib/series/model";
import { TextField } from "./ArticleProperties";
import { ImageUpload } from "./ImageUpload";
export const seriesFields = [["title", "Seri başlığı"], ["summary", "Açıklama"], ["cover", "Kapak görseli"], ["chapters", "Bölümler"], ["meta", "Seri bilgileri"], ["layout", "Sayfa düzeni"]] as const;
export function SeriesProperties({ series, collection, articles, field, onChange }: { series: BlogSeries; collection: readonly BlogSeries[]; articles: readonly Article[]; field: string; onChange: (s: BlogSeries) => void }) {
  const update = (change: Partial<BlogSeries>) => onChange({ ...series, ...change });
  const layout = series.presentation ?? { heading: "left", chapterStyle: "cards" };
  if (field === "title") return <TextField label="Seri başlığı" value={series.title} onChange={(title) => update({ title })} />;
  if (field === "summary") return <TextField label="Seri açıklaması" multiline value={series.summary} onChange={(summary) => update({ summary })} />;
  if (field === "cover") return <>{series.coverImage && <figure className="inline-series-cover"><img src={series.coverImage} alt="Seri kapağı önizlemesi" /></figure>}<ImageUpload label={series.coverImage ? "Kapağı değiştir" : "Kapak görseli yükle"} onUploaded={(coverImage) => update({ coverImage })} />{series.coverImage && <button className="studio-remove" onClick={() => update({ coverImage: undefined })}>Kapağı kaldır</button>}<p className="property-note">JPEG veya PNG, en fazla 10 MiB. Kapak seçilmezse seriye uygun örnek kapak gösterilir.</p></>;
  if (field === "layout") return <><label className="studio-field"><span>Başlık hizası</span><select value={layout.heading} onChange={(e) => update({ presentation: { ...layout, heading: e.target.value as "left" | "center" } })}><option value="left">Sola hizalı</option><option value="center">Ortalanmış</option></select></label><label className="studio-field"><span>Bölüm görünümü</span><select value={layout.chapterStyle} onChange={(e) => update({ presentation: { ...layout, chapterStyle: e.target.value as "cards" | "rows" } })}><option value="cards">Kartlar</option><option value="rows">Editoryal satırlar</option></select></label></>;
  if (field === "meta") return <><TextField label="Kalıcı bağlantı adı" value={series.slug} onChange={(slug) => update({ slug })} /><label className="studio-field"><span>Görünürlük</span><select value={series.status} onChange={(e) => update({ status: e.target.value as BlogSeries["status"] })}><option value="draft">Taslak</option><option value="published">Ziyaretçiye açık</option><option value="archived">Arşiv</option><option value="trashed">Çöp kutusu</option></select></label><label className="document-checkbox"><input type="checkbox" checked={series.ongoing} onChange={(e) => update({ ongoing: e.target.checked })} />Yeni bölümler gelecek</label></>;
  const occupied = new Set(collection.filter((s) => s.id !== series.id).flatMap((s) => s.articleSlugs));
  return <><ol className="document-chapter-list">{series.articleSlugs.map((slug, index) => <li key={slug}><strong>{articles.find((a) => a.slug === slug)?.title}</strong><div className="document-order">{([-1, 1] as const).map((direction) => <button key={direction} disabled={index + direction < 0 || index + direction >= series.articleSlugs.length} aria-label={`Bölüm ${index + 1} ${direction === -1 ? "yukarı" : "aşağı"}`} onClick={() => { const slugs = [...series.articleSlugs]; [slugs[index], slugs[index + direction]] = [slugs[index + direction], slugs[index]]; update({ articleSlugs: slugs }); }}>{direction === -1 ? "↑" : "↓"}</button>)}<button onClick={() => update({ articleSlugs: series.articleSlugs.filter((s) => s !== slug) })}>Seriden çıkar</button></div></li>)}</ol><label className="studio-field"><span>Bölüm ekle</span><select value="" onChange={(e) => { const article = articles.find((item) => item.slug === e.target.value); if (article) update({ articleSlugs: insertChapterByCreation(series.articleSlugs, article, articles) }); }}><option value="">Yazı seç</option>{articles.filter((a) => !series.articleSlugs.includes(a.slug)).map((a) => <option value={a.slug} key={a.slug} disabled={occupied.has(a.slug)}>{a.title}{occupied.has(a.slug) ? " · başka seride" : ""}</option>)}</select></label><p className="property-note">Tuvalde bir bölüme tıklayarak o yazının düzenleme sayfasına geçebilirsin.</p></>;
}
