"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {api,clearCsrf} from "../../lib/api/client";
import {useAuth} from "../auth/AuthProvider";
import {StudioHeader} from "./StudioHeader";
type Section="site"|"categories"|"members"|"stats"|"jobs"|"archives";
type Settings={version:number;authorPublicName:string;seo:{title:string|null;description:string|null;indexable:boolean};indexingEnabled:boolean;canonicalOrigin:string};
type Archive={id:string;state:string;validationVersion:number;downloadUrl?:string;plan?:{counts?:Record<string,number>;errors?:{code:string;slug?:string}[]}};
type Page={items:Record<string,string|number>[];totalPages:number};
const sections:{id:Section;label:string}[]=[{id:"site",label:"Site ve SEO"},{id:"categories",label:"Kategoriler"},{id:"members",label:"Üyeler"},{id:"stats",label:"Yazı istatistikleri"},{id:"jobs",label:"Yayın bildirimleri"},{id:"archives",label:"Yedek ve geri yükleme"}];
export function StudioTools(){
 const auth=useAuth();const [section,setSection]=useState<Section>("site"),[settings,setSettings]=useState<Settings|null>(null),[rows,setRows]=useState<Page|null>(null),[page,setPage]=useState(0),[query,setQuery]=useState(""),[state,setState]=useState(""),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [categoryEdit,setCategoryEdit]=useState<{id:string;version:number}|null>(null);
 const [password,setPassword]=useState(""),[job,setJob]=useState<Archive|null>(null),[kind,setKind]=useState<"imports"|"exports">("exports"),[name,setName]=useState(""),[slug,setSlug]=useState("");const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{const abort=new AbortController();setRows(null);setSettings(null);setError("");if(section==="archives")return;const path=section==="site"?"/studio/site":section==="categories"?"/studio/categories":section==="members"?`/studio/members?page=${page}&size=20${query?`&q=${encodeURIComponent(query)}`:""}`:section==="stats"?`/studio/article-stats?page=${page}&size=20`:`/studio/publication-jobs?page=${page}&size=20${state?`&state=${state}`:""}${query?`&q=${encodeURIComponent(query)}`:""}`;
 void api<Settings|Page>(path,{signal:abort.signal}).then(data=>{if(section==="site")setSettings(data as Settings);else setRows(data as Page);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[section,page,query,state,refresh,auth.session?.profile.id]);
 useEffect(()=>{if(!job||!["PENDING","COMMITTING"].includes(job.state))return;const abort=new AbortController();let tries=0;const timer=setInterval(()=>{if(++tries>60){clearInterval(timer);setNotice("İşlem arka planda sürüyor. Durumu yenileyebilirsin.");return;}void api<Archive>(`/studio/${kind}/${job.id}`,{signal:abort.signal}).then(setJob).catch(e=>{if(!abort.signal.aborted){clearInterval(timer);setError(e.message);}});},2000);return()=>{clearInterval(timer);abort.abort();};},[job?.id,job?.state,kind]);
 async function run(task:()=>Promise<void>){if(busy)return;setBusy(true);setError("");setNotice("");try{await task();}catch(e){setError(e instanceof Error?e.message:"İşlem tamamlanamadı.");}finally{setBusy(false);}}
 function select(id:Section){setCategoryEdit(null);setName("");setSlug("");setSection(id);setPage(0);setQuery("");setState("");setNotice("");setPassword("");}
 if(!auth.session||auth.session.profile.role!=="owner")return <p role="alert">Studio için sahip oturumu gerekiyor.</p>;
 return <main className="studio"><StudioHeader actions={<Link href="/studio" className="studio-text-link">← Editör</Link>} status={<span className="studio-state">Yönetim</span>}/><div className="account-layout"><nav className="account-sections" aria-label="Studio yönetimi">{sections.map(s=><button key={s.id} type="button" aria-current={section===s.id?"page":undefined} onClick={()=>select(s.id)}>{s.label}</button>)}</nav><section className="account-content"><h1>{sections.find(s=>s.id===section)?.label}</h1>{error&&<p role="alert" className="property-note">{error}</p>}{notice&&<p role="status" className="property-note">{notice}</p>}
 {section==="site"&&settings&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{setSettings(await api<Settings>("/studio/site",{method:"PATCH",version:settings.version,body:{authorPublicName:settings.authorPublicName,seo:settings.seo,indexingEnabled:settings.indexingEnabled}}));setNotice("Site ayarları kaydedildi.");});}}><label className="studio-field">Yazar adı<input value={settings.authorPublicName} maxLength={80} onChange={e=>setSettings({...settings,authorPublicName:e.target.value})}/></label><label className="studio-field">Site SEO başlığı<input value={settings.seo.title??""} maxLength={200} onChange={e=>setSettings({...settings,seo:{...settings.seo,title:e.target.value||null}})}/></label><label className="studio-field">Site SEO açıklaması<textarea value={settings.seo.description??""} maxLength={400} onChange={e=>setSettings({...settings,seo:{...settings.seo,description:e.target.value||null}})}/></label><label className="document-checkbox"><input type="checkbox" checked={settings.indexingEnabled} onChange={e=>setSettings({...settings,indexingEnabled:e.target.checked})}/>Yayınlanmış içerikleri arama motorlarına aç</label><p className="property-note">Üretimde INDEXING_ENABLED ayarı da açık olmalıdır. Taslak, planlı ve özel içerikler her durumda kapalıdır. Canonical adres: {settings.canonicalOrigin}</p><button className="studio-primary" disabled={busy}>Kaydet</button></form>}
 {(section==="members"||section==="jobs")&&<form onSubmit={e=>{e.preventDefault();setPage(0);setQuery(new FormData(e.currentTarget).get("q")?.toString().trim()??"");}}><label className="studio-field">{section==="members"?"Ad veya e-posta":"Yazı başlığı"}<input name="q" maxLength={100}/></label><button className="studio-secondary">Ara</button>{section==="members"&&<p className="property-note">Üyelerin özel notları, kitaplıkları ve geçmişleri bu tabloda bulunmaz.</p>}</form>}
 {section==="jobs"&&<label className="studio-field">Durum<select value={state} onChange={e=>{setState(e.target.value);setPage(0);}}><option value="">Tümü</option>{["PENDING","PROCESSING","SENT","SKIPPED","FAILED"].map(s=><option key={s}>{s}</option>)}</select></label>}
 {rows&&<><div className="article-table-scroll" role="region" aria-label={sections.find(s=>s.id===section)?.label} tabIndex={0}><table><thead><tr>{(section==="members"?["Ad","E-posta","Durum","Kayıt tarihi"]:section==="stats"?["Yazı","Görüntülenme","Alkış","Kaydetme"]:section==="categories"?["Ad","Bağlantı","İşlem"]:["Yazı","Durum","Deneme","Tarih","İşlem"]).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.items.map(row=><tr key={row.id??row.articleId}>{(section==="members"?[row.name,row.email,row.status,row.createdAt]:section==="stats"?[row.title,row.views,row.claps,row.saves]:section==="categories"?[row.name,row.slug]:[row.articleTitle??row.aggregateId,row.state,row.attempts,row.createdAt]).map((cell,i)=><td key={i}>{String(cell??"")}</td>)}{section==="jobs"&&<td>{row.state==="FAILED"&&<button disabled={busy} onClick={()=>void run(async()=>{await api(`/studio/publication-jobs/${row.id}/retry`,{method:"POST",idempotencyKey:crypto.randomUUID()});setRefresh(n=>n+1);setNotice("Bildirim yeniden değerlendirilecek.");})}>Yeniden dene</button>}</td>}{section==="categories"&&<td><button disabled={busy} onClick={()=>{setCategoryEdit({id:String(row.id),version:Number(row.version)});setName(String(row.name));setSlug(String(row.slug));}}>Düzenle</button><button disabled={busy} onClick={()=>{if(window.confirm("Kategori kaldırılsın mı? Yazılarda kullanılan kategoriler kaldırılamaz."))void run(async()=>{await api(`/studio/categories/${row.id}`,{method:"DELETE",version:Number(row.version)});setRefresh(n=>n+1);});}}>Kaldır</button></td>}</tr>)}</tbody></table></div>{!rows.items.length&&<p>Henüz kayıt yok.</p>}{rows.totalPages>1&&<nav aria-label="Tablo sayfaları"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>← Önceki</button><span>{page+1} / {rows.totalPages}</span><button disabled={page+1>=rows.totalPages} onClick={()=>setPage(p=>p+1)}>Sonraki →</button></nav>}</>}
 {section==="categories"&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await api(categoryEdit?`/studio/categories/${categoryEdit.id}`:"/studio/categories",{method:categoryEdit?"PATCH":"POST",version:categoryEdit?.version,idempotencyKey:categoryEdit?undefined:crypto.randomUUID(),body:{name,slug}});setCategoryEdit(null);setName("");setSlug("");setRefresh(n=>n+1);setNotice(categoryEdit?"Kategori güncellendi.":"Kategori oluşturuldu.");});}}><label className="studio-field">Kategori adı<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label className="studio-field">Bağlantı adı<input value={slug} maxLength={100} pattern="[a-z0-9]+(-[a-z0-9]+)*" onChange={e=>setSlug(e.target.value)}/></label><button className="studio-primary" disabled={busy||!name.trim()||!slug}>{categoryEdit?"Güncelle":"Oluştur"}</button>{categoryEdit&&<button type="button" className="studio-secondary" onClick={()=>{setCategoryEdit(null);setName("");setSlug("");}}>Vazgeç</button>}</form>}
 {section==="archives"&&<><p className="property-note">İçerikler, seriler, taslak tema ve kullanılan medya. Üye hesapları ve özel üye verileri dahil değildir. Arşivler 24 saat sonra silinir; geri yükleme mevcut yazıları ezmez ve otomatik yayınlamaz.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api("/auth/reauthenticate",{method:"POST",body:{password}});clearCsrf();setPassword("");setNotice("Kimliğin beş dakika için doğrulandı.");});}}><label className="studio-field">Hassas işlemler için güncel şifren<input type="password" autoComplete="current-password" value={password} maxLength={128} onChange={e=>setPassword(e.target.value)}/></label><button className="studio-secondary" disabled={busy||!password}>Kimliğimi doğrula</button></form><button className="studio-primary" disabled={busy} onClick={()=>void run(async()=>{setKind("exports");setJob(await api<Archive>("/studio/exports",{method:"POST",idempotencyKey:crypto.randomUUID()}));})}>İçerik yedeği hazırla</button><label className="studio-field">Geri yükleme arşivi · ZIP, en fazla 100 MiB<input ref={file} type="file" accept=".zip,application/zip"/></label><button className="studio-secondary" disabled={busy} onClick={()=>void run(async()=>{const upload=file.current?.files?.[0];if(!upload)throw new Error("Önce arşiv seç.");if(upload.size>100*1024*1024)throw new Error("Arşiv 100 MiB sınırını aşıyor.");const data=new FormData();data.set("file",upload);setKind("imports");setJob(await api<Archive>("/studio/imports/validate",{method:"POST",idempotencyKey:crypto.randomUUID(),body:data}));})}>Arşivi kontrol et</button>{job&&<section><h2>İşlem durumu: {job.state}</h2><button className="studio-secondary" disabled={busy} onClick={()=>void run(async()=>setJob(await api<Archive>(`/studio/${kind}/${job.id}`)))}>Durumu yenile</button>{job.plan?.counts&&<dl>{Object.entries(job.plan.counts).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}{job.plan?.errors?.map((e,i)=><p key={i} role="alert">{e.code}{e.slug?` · ${e.slug}`:""}</p>)}{job.downloadUrl?.startsWith("/api/v1/studio/exports/")&&<a className="studio-text-link" href={job.downloadUrl}>Yedeği indir</a>}{kind==="imports"&&job.state==="READY"&&<button className="studio-primary" disabled={busy} onClick={()=>{if(window.confirm("Kontrol edilen içerikler taslak olarak geri yüklensin mi? Site indekslemesi kapatılacaktır."))void run(async()=>setJob(await api<Archive>(`/studio/imports/${job.id}/commit`,{method:"POST",idempotencyKey:crypto.randomUUID(),body:{validationVersion:job.validationVersion}})));}}>Taslak olarak geri yükle</button>}</section>}</>}
 </section></div></main>;
}
